"""Build ``libpyrump_oracle`` from the legacy C physics translation units.

This is the unit-level oracle: it exposes ``zstop`` and the fitted stopping-power
polynomials directly, with no TTY, no buffers and no graphics. When a pyRUMP number
disagrees with RUMP, this narrows the cause to a single function.

The library is built twice:

* ``float``  - as RUMP ships (``REAL`` is ``float``, makeosx.h leaves
  ``GPTOPTIONS`` empty so ``-DREAL_IS_DOUBLE`` is never passed)
* ``double`` - with ``-DREAL_IS_DOUBLE``

Comparing the two quantifies RUMP's own single-precision rounding, so a pyRUMP
(float64) discrepancy smaller than that gap is C noise rather than a port bug.

Usage::

    python tests/oracle/build_oracle.py [--out DIR]
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CSRC = HERE / "csrc"

#: The physics translation units. Deliberately excludes sim2.c (command
#: interpreter), rdwr/rbs_rdwr (file I/O) and everything UI.
RUMP_SOURCES = [
    "rump/ziegler.c",
    "rump/stopping.c",
    "rump/sigma.c",
    "rump/atomio.c",
    "rump/atomdo.c",
    "rump/stopfoil.c",
    "rump/reswork.c",  # defines reschk[], read on the simulation path
    "rump/creatr.c",   # the simulation engine itself
]
# Excluded on purpose: rump/stopp.c is the interactive STOPP command shell, not
# physics -- it drags in the whole Lex/Genplot UI for no numerical benefit.

#: Real implementations pulled in rather than stubbed, because the port must
#: reproduce them exactly: FitPolynomial is the weighted least-squares fitter
#: behind the STOP_SQRT refit (stopping.c:536).
SUPPORT_SOURCES = [
    "genplot/gptfit.c",
    "sys/sys_2.c",
    # Reachable from FitPolynomial, so the real implementations are required --
    # the generated ui_stubs.c aborts if one of these is called.
    "complot/minmax.c",   # ArrayMinMax, OrderPair
    "genplot/helper.c",   # g_sppfa/g_sppsl (LINPACK SPD solve), heap_sort
]

BASE_DEFINES = [
    "-DUNIX",
    # mytypes.h only pulls in <stdint.h> under MSC70 or LINUX; without it the
    # build dies on "*** Deal with stdint.h in mytypes.h - FATAL ***".
    "-DLINUX",
    "-DMacInToy",
    "-DGNU_C",
    "-DUNIX_PATH_EXTENSIONS",
    '-DCONFIGPATH="."',
]


def reference_root() -> Path:
    import os

    env = os.environ.get("PYRUMP_C_REFERENCE")
    candidates = [Path(env)] if env else []
    candidates.append(HERE.parents[1] / "C-code")
    for root in candidates:
        if (root / "rump" / "ziegler.c").is_file():
            return root
    raise SystemExit(
        "Legacy C tree not found. Set PYRUMP_C_REFERENCE to the directory "
        "containing rump/ziegler.c."
    )


def collect_headers(root: Path, include_dir: Path) -> None:
    """RUMP expects all headers flattened into one -I directory."""
    include_dir.mkdir(parents=True, exist_ok=True)
    for sub in ("sys", "genplot", "lexp", "complot", "rump"):
        for header in (root / sub).glob("*.h"):
            shutil.copy2(header, include_dir / header.name)


#: Symbols the linker reports as missing that are *data*, not functions. Emitting
#: a function for these would link but corrupt any read of them.
_DATA_STUBS = {
    "RbsConfigPath": 'char *RbsConfigPath = ".";',
    # CAREFUL: these are sim2.c:81-82 and their values are load-bearing.
    # sigtab defaults to -1 meaning "use the built-in analytic cross-section with
    # unit scaling". Zero would instead satisfy `sigtab[itype] >= 0` in
    # SetupSigmaRecoil (sigma.c:163) and silently select the manual-override
    # branch, yielding a cross-section of exactly zero.
    "coffe2": "float coffe2[2] = { 0.0f,  0.0f};",
    "sigtab": "float sigtab[2] = {-1.0f, -1.0f};",
}


def undefined_symbols(objects: list[Path]) -> list[str]:
    """Ask the linker which symbols are still missing."""
    probe = subprocess.run(
        ["cc", "-shared", "-o", os.devnull, *map(str, objects), "-lm"],
        capture_output=True,
        text=True,
    )
    if probe.returncode == 0:
        return []
    found = set(re.findall(r'"_([A-Za-z_][A-Za-z_0-9]*)"', probe.stderr))
    if not found:
        raise SystemExit(f"link failed for reasons other than missing symbols:\n{probe.stderr}")
    return sorted(found)


def render_ui_stubs(names: list[str]) -> str:
    """Emit definitions for unreachable GENPLOT UI symbols.

    Functions abort rather than return: reaching one means the oracle wandered
    into an interactive path, and any number it then produced would be junk.
    """
    lines = [
        "/* GENERATED by build_oracle.py -- do not edit.",
        " *",
        " * The RUMP physics units reference GENPLOT's UI, plotting and expression",
        " * layers from code paths the oracle never executes. macOS resolves dylib",
        " * symbols at load time, so they must exist even though they are unreachable.",
        " */",
        "",
        "#include <stdio.h>",
        "#include <stdlib.h>",
        "",
        "static void ui_unreachable(const char *name) {",
        '\tfprintf(stderr, "pyrump oracle: unreachable UI symbol \'%s\' was called\\n", name);',
        "\tabort();",
        "}",
        "",
    ]
    for name in names:
        if name in _DATA_STUBS:
            lines.append(_DATA_STUBS[name])
    for name in names:
        if name not in _DATA_STUBS:
            lines.append(f'int {name}(void) {{ ui_unreachable("{name}"); return 0; }}')
    return "\n".join(lines) + "\n"


def build(root: Path, out_dir: Path, *, double: bool) -> Path:
    suffix = "double" if double else "float"
    work = out_dir / suffix
    work.mkdir(parents=True, exist_ok=True)
    include_dir = out_dir / "include"
    collect_headers(root, include_dir)

    defines = list(BASE_DEFINES)
    if double:
        defines.append("-DREAL_IS_DOUBLE")

    # -w: the 1990s source is not warning-clean and the noise hides real errors.
    common = ["cc", "-fPIC", "-O2", "-w", *defines, f"-I{include_dir}", f"-I{CSRC}"]

    objects: list[Path] = []
    for rel in RUMP_SOURCES + SUPPORT_SOURCES:
        src = root / rel
        obj = work / (Path(rel).stem + ".o")
        subprocess.run([*common, "-c", str(src), "-o", str(obj)], check=True)
        objects.append(obj)

    for src in (CSRC / "stubs.c", CSRC / "stragf_probe.c", CSRC / "sim_probe.c", CSRC / "oracle_api.c"):
        obj = work / (src.stem + ".o")
        # stragf_probe.c #includes anlyz.c outright, to reach its file-statics,
        # so it needs the rump source directory on the include path.
        extra = [f"-I{root / 'rump'}"] if src.name == "stragf_probe.c" else []
        subprocess.run([*common, *extra, "-c", str(src), "-o", str(obj)], check=True)
        objects.append(obj)

    ext = ".dylib" if sys.platform == "darwin" else ".so"
    lib = out_dir / f"libpyrump_oracle_{suffix}{ext}"

    # The remaining unresolved symbols are GENPLOT UI entry points reached only
    # from interactive code paths. Rather than maintain that list by hand (it
    # shifts whenever a source is added), discover it from the linker and
    # synthesise aborting stubs.
    missing = undefined_symbols(objects)
    stub_src = work / "ui_stubs.c"
    stub_src.write_text(render_ui_stubs(missing))
    stub_obj = work / "ui_stubs.o"
    subprocess.run([*common, "-c", str(stub_src), "-o", str(stub_obj)], check=True)
    objects.append(stub_obj)

    subprocess.run(
        ["cc", "-shared", "-o", str(lib), *map(str, objects), "-lm"], check=True
    )
    return lib


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(HERE / "build"), help="output directory")
    args = parser.parse_args()

    root = reference_root()
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    for double in (False, True):
        lib = build(root, out_dir, double=double)
        print(f"built {lib}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
