"""Generate pyRUMP's ECPSSR ionisation cross-section tables for H+ and 4He.

    pip install numpy scipy xraylib
    python tools/ecpssr/make_tables.py        # writes src/pyrump/data/pixe/

Writes ``ecpssr_H1.csv.gz`` and ``ecpssr_He4.csv.gz``, one row per
(ion, element, subshell, energy):

    ion, Z1, A1_u, Z, element, shell, U_keV, E_MeV, sigma_barn

``E_MeV`` is the ion's total lab energy. Energies are log-spaced at
:data:`PER_DECADE` points per decade, dense enough that interpolating
ln(sigma) linearly in ln(E) is good to a few tenths of a percent. Binding
energies are xraylib's ``EdgeEnergy`` -- the same edges as pyRUMP's X-ray
tables (``tools/pixe_atomic.py``). The numerical L-shell form factors are
cached in ``gos_20.npz``/``gos_21.npz`` next to this file (not in git;
recomputed in about 11 minutes when missing). See README.md for the theory
and its validation.
"""

import argparse
import csv
import gzip

from datetime import date
from pathlib import Path

import numpy as np
import xraylib as xr

from ecpssr import ecpssr

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = ROOT / "src" / "pyrump" / "data" / "pixe"

#: Points per decade of ion energy.
PER_DECADE = 50

IONS = {
    "H1": dict(Z1=1, A1=1.007276467, E_min=0.1, E_max=5.0),
    "He4": dict(Z1=2, A1=4.001506179, E_min=0.2, E_max=12.0),
}
SHELLS = [("K", xr.K_SHELL, 6, 92), ("L1", xr.L1_SHELL, 18, 92),
          ("L2", xr.L2_SHELL, 18, 92), ("L3", xr.L3_SHELL, 18, 92)]


def energies(e_min: float, e_max: float) -> np.ndarray:
    n = int(round(np.log10(e_max / e_min) * PER_DECADE)) + 1
    return np.geomspace(e_min, e_max, n)


def main(out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    for ion, p in IONS.items():
        path = out / f"ecpssr_{ion}.csv.gz"
        grid = energies(p["E_min"], p["E_max"])
        n = 0
        with gzip.open(path, "wt", encoding="utf-8", newline="") as handle:
            handle.write(
                f"# ECPSSR ionisation cross sections, {ion}. Generated by tools/ecpssr/make_tables.py\n"
                f"# on {date.today()} (binding energies: xraylib {xr.__version__} EdgeEnergy).\n"
                "# Brandt & Lapicki ECPSSR, own implementation; no ISICS or GUPIX code or data.\n"
            )
            w = csv.writer(handle, lineterminator="\n")
            w.writerow(["ion", "Z1", "A1_u", "Z", "element", "shell", "U_keV", "E_MeV", "sigma_barn"])
            for shell, xs, zmin, zmax in SHELLS:
                for Z in range(zmin, zmax + 1):
                    U = xr.EdgeEnergy(Z, xs)
                    A2 = xr.AtomicWeight(Z)
                    sym = xr.AtomicNumberToSymbol(Z)
                    for E in grid:
                        s = ecpssr(shell, p["Z1"], p["A1"], Z, A2, float(E), U)
                        w.writerow([ion, p["Z1"], p["A1"], Z, sym, shell, f"{U:.4f}",
                                    f"{E:.6g}", f"{s:.6e}"])
                        n += 1
                print(f"  {ion} {shell} done", flush=True)
        print(path, n, "rows", flush=True)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("out", nargs="?", type=Path, default=DEFAULT_OUT)
    main(parser.parse_args().out)
