Empty File 'c:\RBS\data\2022\01\MnPt.RBS
Identifier 'MnPt.RBS  170 Degree RBS LT =  2457.874 RT  2463.078 Gain  2
Date       '11:01:23  01-01-2022
Conversion  1.59             48 
MeV 1.902
Beam He+
Geometry General
Theta -09.0
Phi  11
Psi 20.0
Omega 2.7
Choff 0 FWHM 15
Current 004.31
Charge 16
Swallow
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 12989         17802         16765         15328 
 13967         12679         11136         9892 
 8893          7856          7271          6565 
 6013          5805          5419          5152 
 4876          4776          4479          4489 
 4380          4297          4197          4058 
 3996          4005          3904          3793 
 3704          3673          3611          3634 
 3583          3645          3450          3454 
 3395          3331          3431          3251 
 3318          3222          3233          3205 
 3208          3149          3129          3032 
 3006          2978          3013          2875 
 2977          2924          2884          2910 
 2943          2877          2764          2866 
 2652          2680          2738          2794 
 2604          2719          2688          2721 
 2611          2555          2540          2612 
 2494          2565          2434          2483 
 2499          2466          2477          2476 
 2414          2352          2283          2336 
 2438          2259          2366          2346 
 2291          2314          2289          2340 
 2343          2145          2252          2268 
 2250          2240          2158          2276 
 2202          2106          2141          2108 
 2135          2182          2106          2092 
 2101          2140          2145          2036 
 2139          2100          2069          2044 
 2078          2082          2039          1954 
 1999          2034          2052          1892 
 1962          2034          1994          1981 
 1858          1994          2023          1895 
 1971          1946          2012          1852 
 1927          1935          1895          1896 
 1905          1823          1931          1822 
 1761          1911          1805          1802 
 1871          1813          1771          1858 
 1874          1781          1830          1818 
 1860          1820          1803          1813 
 1802          1764          1790          1781 
 1748          1785          1735          1834 
 1846          1750          1767          1752 
 1748          1721          1761          1734 
 1761          1807          1724          1728 
 1778          1699          1723          1791 
 1793          1651          1642          1747 
 1672          1633          1734          1661 
 1681          1642          1669          1680 
 1675          1649          1674          1679 
 1754          1707          1756          1646 
 1686          1612          1568          1649 
 1627          1606          1594          1681 
 1609          1689          1721          1602 
 1686          1640          1702          1669 
 1694          1685          1589          1622 
 1729          1593          1645          1552 
 1633          1595          1648          1607 
 1639          1545          1685          1659 
 1709          1559          1548          1579 
 1638          1603          1514          1578 
 1614          1535          1531          1575 
 1632          1558          1624          1527 
 1573          1632          1513          1587 
 1595          1592          1563          1563 
 1571          1610          1582          1572 
 1595          1567          1584          1588 
 1522          1577          1624          1557 
 1573          1519          1501          1529 
 1565          1487          1510          1498 
 1534          1585          1563          1574 
 1516          1496          1529          1521 
 1488          1441          1468          1516 
 1539          1542          1428          1513 
 1526          1435          1560          1502 
 1513          1533          1538          1465 
 1540          1504          1562          1563 
 1507          1502          1507          1522 
 1498          1462          1446          1559 
 1486          1522          1579          1507 
 1570          1485          1573          1591 
 1524          1529          1538          1600 
 1609          1637          1627          1684 
 1589          1639          1593          1663 
 1603          1621          1612          1572 
 1571          1578          1608          1444 
 1458          1548          1509          1568 
 1537          1483          1484          1496 
 1461          1491          1502          1475 
 1455          1441          1491          1396 
 1527          1490          1489          1428 
 1449          1497          1516          1468 
 1452          1462          1453          1455 
 1504          1397          1470          1412 
 1340          1488          1438          1447 
 1416          1467          1448          1445 
 1373          1426          1438          1424 
 1374          1408          1404          1448 
 1462          1385          1439          1498 
 1466          1395          1478          1453 
 1384          1449          1397          1304 
 1438          1462          1405          1478 
 1421          1395          1414          1424 
 1491          1429          1423          1392 
 1413          1459          1351          1386 
 1322          1436          1413          1379 
 1400          1382          1378          1397 
 1382          1443          1464          1392 
 1358          1387          1445          1440 
 1394          1403          1407          1451 
 1394          1463          1402          1434 
 1361          1439          1400          1355 
 1417          1374          1397          1430 
 1347          1374          1398          1412 
 1403          1329          1311          1432 
 1386          1405          1353          1400 
 1328          1439          1332          1351 
 1427          1380          1413          1373 
 1343          1365          1381          1405 
 1450          1359          1427          1395 
 1293          1375          1400          1341 
 1341          1366          1398          1314 
 1371          1331          1392          1352 
 1312          1298          1354          1361 
 1418          1295          1392          1376 
 1405          1334          1330          1432 
 1430          1291          1361          1343 
 1316          1359          1306          1333 
 1263          1341          1345          1423 
 1350          1278          1374          1280 
 1289          1306          1288          1312 
 1334          1365          1280          1296 
 1383          1322          1386          1348 
 1297          1344          1304          1269 
 1352          1301          1367          1334 
 1302          1264          1255          1315 
 1371          1294          1363          1343 
 1350          1300          1308          1258 
 1306          1338          1248          1272 
 1238          1242          1251          1252 
 1188          1195          1135          1055 
 1075          1030          973           888 
 816           801           765           688 
 656           578           485           481 
 381           327           318           272 
 243           203           172           130 
 112           102           103           89 
 73            69            62            53 
 41            40            41            35 
 32            30            35            19 
 30            16            18            9 
 17            20            7             9 
 10            7             5             7 
 6             6             7             5 
 7             3             3             7 
 11            3             1             3 
 3             1             1             5 
 1             4             3             2 
 3             6             5             3 
 2             5             3             4 
 2             7             1             3 
 3             3             5             2 
 5             3             4             1 
 2             3             3             2 
 6             0             3             2 
 2             4             2             5 
 3             3             2             4 
 3             6             5             0 
 3             4             4             6 
 2             3             3             2 
 0             3             2             1 
 1             3             2             3 
 3             7             2             2 
 3             4             1             0 
 2             2             1             5 
 3             1             4             4 
 3             2             2             2 
 4             5             5             4 
 7             4             7             1 
 3             5             7             8 
 4             2             3             4 
 2             3             1             4 
 4             4             3             1 
 4             2             3             3 
 1             2             3             3 
 2             2             6             3 
 1             4             4             4 
 4             1             2             3 
 3             3             2             5 
 4             5             2             3 
 3             5             6             3 
 7             1             6             7 
 1             3             2             9 
 9             8             7             9 
 8             11            16            17 
 31            29            25            35 
 42            61            98            113 
 121           170           189           278 
 363           457           502           629 
 664           808           1019          1038 
 1106          1208          1286          1407 
 1414          1519          1490          1597 
 1618          1624          1664          1539 
 1575          1519          1537          1489 
 1429          1432          1278          1189 
 1065          950           802           771 
 633           547           409           329 
 281           225           183           138 
 99            60            54            55 
 27            19            27            26 
 17            14            10            11 
 5             6             4             4 
 4             2             6             3 
 3             1             3             4 
 5             4             4             4 
 1             4             2             7 
 2             6             1             3 
 2             3             4             3 
 5             5             5             6 
 8             4             2             2 
 3             3             8             10 
 3             4             9             11 
 6             6             11            5 
 9             12            19            16 
 14            25            23            39 
 25            48            63            79 
 83            115           131           199 
 224           299           345           432 
 504           591           662           784 
 883           941           958           1106 
 1168          1194          1155          1101 
 1039          973           942           796 
 751           631           550           508 
 427           387           303           274 
 292           345           391           426 
 493           528           668           712 
 870           996           1034          1164 
 1117          1157          1180          1149 
 1119          1041          948           878 
 766           639           525           480 
 404           355           246           197 
 142           111           93            72 
 50            35            39            29 
 28            30            20            25 
 24            25            26            38 
 30            47            47            66 
 56            76            98            112 
 140           161           255           319 
 407           478           654           798 
 1062          1297          1557          1857 
 2181          2550          2812          3188 
 3654          4000          4303          4573 
 4730          5013          5236          5338 
 5393          5682          5523          5634 
 5544          5748          5537          5400 
 5394          5209          4998          4875 
 4485          4085          3837          3547 
 2995          2721          2289          1910 
 1585          1284          1116          801 
 701           515           380           289 
 216           162           127           86 
 58            50            44            29 
 17            11            15            15 
 8             7             4             6 
 3             7             5             2 
 3             5             2             3 
 4             2             1             1 
 1             4             4             4 
 1             4             4             6 
 1             1             3             1 
 0             3             4             3 
 2             3             2             0 
 0             1             3             2 
 2             4             1             0 
 0             3             0             2 
 1             0             3             3 
 4             2             1             2 
 1             2             1             1 
 1             0             3             1 
 0             2             0             0 
 1             0             0             2 
 1             2             3             1 
 3             2             0             2 
 1             1             0             2 
 2             1             1             0 
 0             0             4             0 
 1             0             1             2 
 2             1             0             3 
 0             1             0             2 
 0             0             4             1 
 1             2             2             3 
 2             0             0             0 
 1             1             0             2 
 1             0             0             1 
 0             0             2             0 
 1             2             1             0 
 1             0             0             1 
 0             0             0             3 
 2             2             0             1 
 1             1             0             1 
 2             1             0             0 
 0             2             1             0 
 1             0             0             1 
 0             1             0             0 
 2             0             0             0 
 0             0             0             0 
 0             1             1             0 
 0             1             0             0 
 0             0             0             1 
 0             0             2             2 
 2             2             1             1 
 0             2             0             0 
 0             0             0             0 
 1             1             0             2 
 1             3             0             1 
 0             0             1             0 
 1             0             0             0 
 2             0             1             1 
 1             1             2             1 
 1             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             2 
 0             0             0             0 
 1             2             1             0 
 0             0             1             0 
 0             1             1             0 
 0             0             0             1 
 0             0             0             0 
 1             1             0             0 
 2             0             0             0 
 0             0             0             0 
 0             0             1             0 
 0             1             1             0 
 0             1             1             0 
 0             0             0             0 
 0             0             1             0 
 0             0             0             0 
 0             0             0             0 
 0             1             0             0 
 0             1             0             0 
 1             0             2             1 
 1             0             1             0 
 0             0             0             0 
 1             0             1             0 
 1             0             0             0 
 0             0             0             0 
 0             0             0             1 
 0             0             1             0 
 0             0             0             0 
 0             0             0             0 
 0             0             2             0 
 0             0             0             1 
 0             0             0             1 
 0             0             0             0 
 0             0             2             1 
 0             0             0             0 
 2             0             0             0 
 0             0             0             0 
 1             0             1             2 
 1             0             0             0 
 0             0             0             1 
 0             1             0             0 
 0             0             1             0 
 0             0             0             0 
 0             0             0             0 
 0             1             0             1 
 2             0             0             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 1             0             0             0 
 0             0             0             0 
 0             1             1             0 
 0             0             1             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             1 
 0             0             0             0 
 1             1             0             0 
 0             0             0             0 
 0             1             0             1 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             1             1             0 
 0             0             1             0 
 0             1             0             0 
 0             1             0             0 
 0             1             0             0 
 0             0             0             0 
 1             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             1             0 
 0             0             1             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             1             0             0 
 1             1             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             1             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             1             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             1             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             1             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 1             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             1             1 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             1             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 1             0             0             0 
 0             0             0             0 
 0             1             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 1             0             1             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             1             0 
 0             0             0             0 
 0             0             0             0 


