Empty File 'c:\data\2026\01\MA8444.RBS
Identifier 'MnPt.RBS  170 Degree RBS LT =  1113.102 RT  1115.404 Gain  2
Date       '14:14:57  09-01-2026
Conversion  1.59             48 
MeV 1.902
Beam He+
Geometry General
Theta  01.0
Phi  11
Psi 10.0
Omega 2.7
Choff 0 FWHM 15
Current 008.87
Charge 10
Swallow
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 10328         13015         11106         8887 
 6955          5560          4602          4012 
 3578          3287          3131          2951 
 2779          2732          2509          2503 
 2573          2509          2434          2401 
 2245          2397          2349          2253 
 2291          2244          2181          2211 
 2093          2042          2126          2064 
 2017          2047          2001          1974 
 1972          1906          1947          1831 
 1857          1854          1892          1820 
 1791          1813          1795          1723 
 1791          1748          1645          1658 
 1681          1690          1563          1688 
 1679          1616          1573          1567 
 1575          1546          1526          1593 
 1585          1583          1540          1452 
 1535          1520          1473          1484 
 1442          1431          1501          1404 
 1420          1454          1396          1440 
 1346          1361          1393          1335 
 1385          1330          1363          1337 
 1307          1282          1363          1332 
 1291          1240          1278          1330 
 1307          1288          1212          1304 
 1293          1346          1192          1236 
 1236          1241          1270          1200 
 1245          1280          1266          1253 
 1305          1184          1183          1192 
 1186          1192          1149          1226 
 1176          1154          1162          1060 
 1134          1137          1130          1097 
 1134          1134          1138          1102 
 1146          1057          1111          1061 
 1066          1096          1045          1073 
 1076          1116          1106          1144 
 1057          1090          1040          1108 
 1077          1013          993           1070 
 1073          1055          1091          1022 
 1023          1031          1033          1058 
 1040          1020          1040          1028 
 996           1072          1013          1011 
 1045          975           967           965 
 1037          1018          1025          1004 
 1004          987           952           934 
 1030          1035          955           1014 
 994           960           1021          1038 
 939           938           943           998 
 942           945           937           958 
 940           987           919           906 
 988           930           924           933 
 959           966           999           949 
 923           951           953           934 
 922           959           953           936 
 906           928           922           888 
 890           943           947           923 
 872           894           925           925 
 937           945           847           922 
 928           878           973           931 
 937           909           955           899 
 910           906           904           889 
 884           891           891           909 
 875           907           895           882 
 927           927           881           919 
 878           919           895           912 
 921           850           905           908 
 897           898           873           887 
 910           830           827           879 
 898           903           896           900 
 886           913           831           890 
 838           879           867           868 
 878           855           869           885 
 890           828           886           890 
 918           867           947           857 
 848           796           867           811 
 816           856           876           850 
 829           837           836           886 
 825           802           869           881 
 859           873           830           872 
 860           866           798           813 
 875           810           853           879 
 771           827           800           857 
 826           874           921           876 
 906           886           874           967 
 906           893           966           893 
 950           918           936           1007 
 936           886           905           870 
 869           796           869           806 
 791           851           853           855 
 786           867           794           882 
 833           798           854           828 
 830           805           832           737 
 844           834           824           819 
 847           809           806           821 
 827           800           757           858 
 799           801           843           801 
 779           841           839           842 
 774           841           842           800 
 837           829           822           810 
 855           824           765           768 
 824           856           813           829 
 823           805           768           736 
 751           755           794           776 
 758           827           794           821 
 737           854           776           805 
 780           836           785           804 
 792           822           759           780 
 847           746           779           802 
 783           778           794           791 
 769           831           796           782 
 791           815           770           753 
 784           816           788           768 
 809           751           765           769 
 773           765           795           830 
 770           765           738           781 
 753           760           739           759 
 793           804           736           772 
 785           771           828           782 
 775           777           770           816 
 759           774           755           821 
 798           724           800           799 
 744           768           749           809 
 749           763           772           746 
 766           791           783           814 
 813           773           784           755 
 749           746           837           737 
 677           756           757           724 
 676           787           773           788 
 721           774           766           746 
 784           809           781           771 
 749           788           793           797 
 796           748           745           755 
 726           729           773           747 
 752           795           787           761 
 710           776           765           753 
 771           801           733           751 
 753           744           752           770 
 704           771           735           770 
 736           764           760           767 
 748           732           764           777 
 735           819           748           795 
 713           695           708           719 
 738           716           707           695 
 686           649           567           568 
 622           498           461           449 
 413           317           316           288 
 297           230           193           169 
 140           104           107           81 
 79            86            62            50 
 48            47            28            31 
 35            42            20            22 
 22            19            13            13 
 14            12            13            9 
 9             8             10            5 
 4             6             2             1 
 4             4             2             0 
 1             1             0             1 
 1             1             1             3 
 2             1             3             3 
 1             0             3             1 
 3             0             2             0 
 2             0             2             4 
 2             2             1             2 
 2             2             3             1 
 1             2             0             2 
 0             1             2             3 
 0             0             1             3 
 1             1             1             4 
 1             2             2             0 
 2             2             0             3 
 1             0             2             3 
 1             4             0             0 
 0             1             0             0 
 1             2             1             1 
 2             2             0             3 
 2             0             3             1 
 0             0             1             4 
 1             1             3             1 
 0             1             1             3 
 1             1             3             0 
 2             1             2             1 
 0             4             2             3 
 3             1             4             1 
 4             1             1             4 
 1             3             0             0 
 0             1             2             2 
 1             2             1             1 
 0             2             1             0 
 0             1             2             0 
 1             0             2             2 
 7             1             1             2 
 2             4             1             5 
 1             0             2             6 
 0             2             3             2 
 3             4             9             1 
 5             3             4             10 
 8             4             15            6 
 12            14            21            28 
 27            48            59            78 
 102           116           160           173 
 217           314           387           381 
 460           593           654           720 
 758           812           897           980 
 1012          987           1077          1097 
 970           1059          981           926 
 864           850           760           699 
 637           531           470           367 
 323           270           208           161 
 146           92            80            62 
 46            38            29            16 
 15            11            4             9 
 7             3             3             1 
 6             4             3             2 
 2             3             1             3 
 3             2             2             1 
 0             0             3             1 
 2             6             4             1 
 1             0             0             2 
 2             2             1             1 
 1             1             2             1 
 1             0             0             6 
 1             3             3             3 
 3             3             6             3 
 0             8             6             2 
 4             5             2             7 
 9             7             14            12 
 8             13            17            20 
 35            36            49            50 
 48            85            113           89 
 177           175           234           259 
 330           402           472           465 
 552           677           659           791 
 778           810           816           814 
 833           743           732           689 
 664           576           523           488 
 491           502           440           465 
 508           571           584           675 
 687           760           756           806 
 838           820           837           817 
 748           658           605           531 
 450           400           306           216 
 186           162           115           83 
 83            62            36            39 
 29            18            20            15 
 9             10            7             8 
 15            16            14            14 
 12            17            17            19 
 24            25            25            34 
 35            52            73            70 
 91            137           147           189 
 232           303           395           479 
 633           750           928           1105 
 1380          1600          1908          2125 
 2333          2619          2804          3148 
 3296          3414          3616          3571 
 3684          3674          3612          3565 
 3499          3268          3226          3005 
 2822          2555          2390          2090 
 1699          1489          1227          1030 
 833           698           538           370 
 313           252           186           130 
 96            87            65            38 
 29            17            20            12 
 7             10            9             4 
 4             2             2             3 
 1             1             4             0 
 0             2             2             2 
 1             0             1             1 
 2             1             0             1 
 3             1             2             0 
 1             1             3             2 
 0             2             0             0 
 1             0             1             1 
 1             4             1             0 
 2             0             0             1 
 2             1             1             0 
 0             1             2             2 
 2             1             1             1 
 2             3             0             1 
 3             2             0             0 
 0             1             1             3 
 1             0             1             0 
 2             0             2             1 
 3             0             1             1 
 1             0             0             1 
 0             3             1             0 
 0             1             0             0 
 1             0             0             2 
 1             0             2             3 
 0             1             1             2 
 0             1             0             0 
 0             1             1             1 
 2             0             0             1 
 1             0             0             0 
 0             1             0             0 
 1             0             1             1 
 0             0             0             0 
 1             1             1             0 
 1             0             0             0 
 0             0             0             0 
 1             0             1             0 
 1             0             0             0 
 0             1             1             2 
 1             0             2             0 
 0             0             0             2 
 0             0             2             0 
 2             0             0             0 
 1             0             0             0 
 0             1             1             1 
 1             0             1             2 
 2             1             0             0 
 0             0             0             0 
 0             1             0             0 
 0             1             0             0 
 0             0             2             0 
 0             1             2             0 
 0             0             1             3 
 1             1             0             1 
 1             0             0             2 
 0             0             0             1 
 0             0             0             0 
 0             0             0             1 
 0             1             0             0 
 0             0             0             0 
 2             2             0             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             1             1             0 
 0             1             1             1 
 1             0             0             1 
 1             1             0             0 
 0             0             0             0 
 1             0             0             0 
 0             0             1             0 
 0             0             0             0 
 0             1             0             0 
 0             0             0             0 
 0             0             1             0 
 0             0             0             0 
 0             0             1             0 
 1             0             0             0 
 0             0             0             0 
 0             0             1             0 
 0             1             1             0 
 0             0             0             0 
 1             1             1             0 
 2             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             1             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             1             1 
 0             0             2             0 
 0             0             0             0 
 0             0             0             1 
 0             0             2             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             1 
 0             1             0             0 
 0             0             0             0 
 0             0             1             0 
 1             0             0             0 
 0             0             0             0 
 0             0             1             0 
 1             0             1             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             1             0 
 0             1             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             1             0 
 0             0             0             0 
 0             0             0             2 
 0             0             0             0 
 0             0             1             1 
 0             0             0             0 
 1             0             1             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 1             0             0             0 
 1             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             1             0 
 1             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             1             0             0 
 0             0             0             0 
 0             1             0             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             1             0 
 0             0             0             0 
 0             1             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 2             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 1             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 


