Empty File 'Sample1.RBS
Identifier 'Sample1  170 Degree RBS LT =  691.736 RT  693.536
Date       '14:00:00  01-01-2020
Conversion  1.45             66 
MeV 1.900
Beam He+
Geometry General
Theta -09.0
Phi  11
Psi 20.0
Omega 2.78
Choff 0 FWHM 18
Current 055.54
Charge 40
Swallow
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             4005          7806          10232 
 12363         14231         15587         16218 
 16354         16349         15814         15853 
 15408         14895         14709         14487 
 13951         13688         13424         13308 
 13024         12726         12537         12386 
 11935         11941         11753         11494 
 11222         11240         11061         10850 
 10751         10451         10437         10211 
 10047         10044         9957          9816 
 9689          9541          9461          9585 
 9209          8931          8977          8856 
 8764          8892          8668          8506 
 8473          8367          8390          8366 
 8125          8144          8036          8043 
 7903          7774          7789          7776 
 7747          7611          7604          7340 
 7242          7293          7176          7331 
 7254          7127          7099          7202 
 6907          7076          6973          6906 
 6798          6667          6679          6665 
 6689          6627          6570          6641 
 6629          6537          6376          6457 
 6426          6297          6329          6273 
 6162          6151          6410          6233 
 6110          5988          5916          6022 
 5852          5897          5968          5847 
 6028          5818          5701          5779 
 5725          5819          5694          5640 
 5559          5533          5662          5441 
 5598          5598          5582          5411 
 5415          5419          5427          5288 
 5380          5373          5139          5314 
 5333          5408          5183          5202 
 5307          5116          5095          5116 
 5273          5070          5042          5065 
 5029          5031          5099          5045 
 5027          5032          4944          5045 
 4964          5038          4873          5042 
 4864          4849          4868          4769 
 4818          4915          5002          4735 
 4731          4664          4914          4787 
 4750          4682          4792          4749 
 4628          4687          4550          4717 
 4597          4527          4553          4609 
 4666          4646          4516          4596 
 4591          4518          4613          4497 
 4490          4509          4482          4410 
 4441          4473          4507          4403 
 4297          4401          4402          4389 
 4355          4434          4432          4426 
 4336          4404          4360          4320 
 4302          4309          4405          4366 
 4275          4191          4249          4294 
 4434          4191          4227          4289 
 4171          4260          4259          4262 
 4229          4257          4222          4158 
 4224          4183          4193          4317 
 4252          4135          4077          4059 
 4196          4132          4085          4220 
 4085          4187          4177          4100 
 4171          4194          4144          4032 
 4058          4170          4189          4124 
 4016          4075          4197          3954 
 4147          4010          4008          4071 
 4048          4050          3985          4021 
 3971          3895          4002          4018 
 3965          3938          4038          4018 
 3966          4014          4068          4114 
 3972          4003          4034          3916 
 3996          4020          3934          3989 
 3825          3888          3874          3986 
 3938          3898          3906          3835 
 4079          3949          3857          3930 
 3852          3877          3980          3951 
 3943          3976          3742          3894 
 3830          3763          3879          3789 
 3871          3837          3864          3841 
 3873          3935          3855          3927 
 3732          3929          3725          3986 
 3801          3881          3881          3881 
 3829          3730          3828          3778 
 3933          3771          3737          3888 
 3762          3864          3909          3885 
 3737          3843          3884          3748 
 3774          3809          3794          3736 
 3808          3746          3610          3784 
 3778          3724          3878          3783 
 3766          3743          3760          3725 
 3749          3680          3790          3694 
 3747          3777          3696          3721 
 3778          3797          3796          3826 
 3830          3892          3932          3939 
 3987          4024          4153          4057 
 4072          4256          4212          4251 
 4185          4153          4037          4099 
 4056          3990          3890          3829 
 3758          3874          3834          3725 
 3755          3764          3672          3675 
 3632          3651          3697          3731 
 3708          3586          3577          3743 
 3605          3734          3782          3655 
 3710          3606          3643          3717 
 3647          3683          3597          3470 
 3582          3585          3539          3553 
 3539          3590          3566          3696 
 3665          3629          3677          3633 
 3559          3577          3630          3663 
 3609          3641          3685          3673 
 3535          3669          3643          3624 
 3677          3710          3564          3602 
 3629          3600          3576          3592 
 3651          3540          3522          3575 
 3537          3519          3594          3579 
 3643          3549          3587          3539 
 3521          3625          3584          3636 
 3694          3632          3495          3572 
 3531          3601          3463          3441 
 3555          3516          3580          3547 
 3648          3606          3626          3599 
 3526          3581          3531          3501 
 3560          3591          3505          3537 
 3502          3537          3556          3543 
 3602          3629          3594          3490 
 3401          3440          3450          3495 
 3640          3484          3642          3508 
 3596          3523          3486          3472 
 3504          3542          3520          3538 
 3468          3541          3527          3409 
 3394          3565          3443          3418 
 3523          3511          3570          3572 
 3508          3462          3604          3467 
 3577          3488          3504          3581 
 3485          3579          3398          3535 
 3461          3527          3414          3564 
 3491          3535          3633          3485 
 3464          3511          3512          3475 
 3397          3500          3447          3400 
 3488          3573          3550          3399 
 3431          3467          3426          3390 
 3499          3395          3545          3459 
 3413          3477          3399          3435 
 3463          3458          3498          3442 
 3429          3396          3426          3487 
 3382          3526          3508          3436 
 3542          3498          3523          3439 
 3571          3588          3351          3464 
 3435          3477          3489          3384 
 3371          3420          3566          3455 
 3407          3465          3394          3435 
 3437          3437          3471          3458 
 3327          3380          3408          3456 
 3524          3390          3407          3449 
 3415          3452          3409          3369 
 3288          3399          3419          3381 
 3329          3350          3342          3417 
 3338          3364          3314          3160 
 3015          3030          2889          2764 
 2629          2477          2316          2211 
 2032          1891          1701          1578 
 1468          1240          1114          1035 
 797           776           662           560 
 501           416           388           346 
 298           254           252           253 
 202           223           202           164 
 164           128           158           133 
 111           128           106           118 
 103           95            88            74 
 78            57            59            62 
 57            56            49            45 
 44            43            53            48 
 39            46            43            48 
 39            39            47            43 
 38            37            39            36 
 36            31            40            40 
 29            41            35            44 
 34            45            49            37 
 30            27            35            34 
 40            41            24            25 
 31            36            44            37 
 40            40            32            30 
 31            31            27            23 
 42            23            39            28 
 38            28            31            31 
 34            21            20            28 
 28            32            23            27 
 21            25            36            30 
 27            25            24            30 
 34            29            25            29 
 34            24            22            27 
 25            30            29            37 
 27            22            36            18 
 22            19            26            25 
 29            25            22            26 
 25            27            30            27 
 24            27            20            33 
 32            22            24            34 
 19            27            17            18 
 27            25            24            30 
 19            25            16            24 
 24            24            33            24 
 25            27            28            26 
 30            22            16            15 
 27            27            20            17 
 26            16            19            29 
 21            23            25            14 
 23            17            20            21 
 14            22            21            19 
 27            14            24            27 
 26            24            23            24 
 25            27            18            24 
 23            21            22            22 
 29            27            28            34 
 18            31            22            35 
 27            26            34            26 
 26            35            38            33 
 38            37            50            33 
 41            54            53            74 
 78            103           135           163 
 199           247           357           456 
 611           803           998           1300 
 1566          1844          2317          2720 
 3063          3430          3861          4105 
 4429          4738          4868          4913 
 5071          5028          5125          5020 
 5059          4912          4694          4391 
 4118          3769          3350          3033 
 2570          2094          1796          1409 
 1152          888           698           533 
 448           334           244           181 
 161           121           140           67 
 67            58            49            45 
 52            42            30            35 
 43            39            35            44 
 52            45            52            62 
 72            81            85            109 
 123           152           185           203 
 308           386           429           505 
 577           670           859           884 
 1075          1095          1243          1320 
 1514          1592          1762          1802 
 1875          1962          2071          2073 
 2234          2166          2123          2055 
 1953          1981          1927          1821 
 1698          1663          1513          1381 
 1216          1123          967           879 
 781           654           539           462 
 324           301           245           193 
 158           135           121           91 
 78            55            62            42 
 48            34            29            23 
 30            29            40            32 
 29            17            30            29 
 19            25            31            30 
 26            33            24            23 
 30            35            26            34 
 24            23            25            20 
 31            25            21            19 
 21            34            26            28 
 22            23            23            21 
 27            28            39            30 
 29            35            30            29 
 18            36            32            25 
 36            37            37            18 
 40            41            35            42 
 36            52            50            40 
 49            47            48            59 
 42            68            65            73 
 80            55            81            101 
 74            96            97            96 
 132           128           142           161 
 182           222           259           286 
 344           403           537           727 
 863           1191          1524          2076 
 2650          3569          4591          5831 
 7326          9119          10858         12921 
 14724         16631         18492         19727 
 20643         20704         20259         20034 
 18873         17427         15650         13723 
 11596         9915          8355          6917 
 5783          4821          4221          3964 
 4011          4188          4684          5585 
 6967          8270          10201         12293 
 14553         16774         18438         20372 
 21213         21911         21891         21422 
 19817         18314         16144         13751 
 11711         9512          7574          6036 
 4839          3701          2955          2325 
 1737          1382          1106          857 
 625           504           420           267 
 235           195           154           127 
 126           91            95            104 
 89            86            84            82 
 83            69            82            82 
 81            92            82            78 
 53            78            72            62 
 87            63            61            70 
 68            58            60            66 
 65            70            70            62 
 59            64            66            61 
 72            59            70            49 
 49            74            55            49 
 60            62            61            61 
 72            50            40            56 
 59            42            56            51 
 59            50            48            48 
 57            46            57            61 
 51            46            39            47 
 43            61            45            40 
 38            43            42            36 
 48            36            46            46 
 40            53            46            38 
 34            38            46            44 
 52            52            40            39 
 31            41            33            49 
 35            37            36            34 
 32            46            37            45 
 42            34            35            30 
 41            27            41            37 
 34            43            32            34 
 32            27            54            40 
 30            31            40            33 
 33            36            27            32 
 38            35            37            36 
 36            43            31            43 
 27            34            23            43 
 34            29            40            28 
 34            36            25            36 
 40            33            39            36 
 37            36            35            27 
 19            16            34            26 
 39            33            21            34 
 31            25            30            29 
 20            37            37            31 
 22            22            31            20 
 17            30            24            30 
 29            28            22            28 
 20            32            31            24 
 22            23            20            27 
 28            37            23            20 
 15            20            23            25 
 22            19            13            30 
 20            27            22            19 
 20            29            19            22 
 22            22            29            20 
 24            20            22            28 
 21            24            18            17 
 31            26            24            24 
 22            19            22            24 
 24            26            24            28 
 17            24            25            22 
 26            20            28            13 
 24            13            20            18 
 19            18            25            21 
 18            26            19            17 
 15            21            19            19 
 18            26            23            13 
 24            17            19            14 
 14            22            18            16 
 22            17            22            25 
 13            15            15            18 
 16            17            24            18 
 15            7             18            21 
 18            20            15            19 
 17            17            15            12 
 18            25            15            18 
 15            18            15            23 
 14            19            13            8 
 17            15            20            12 
 16            7             23            19 
 23            17            17            20 
 18            14            12            15 
 19            13            15            12 
 22            12            13            18 
 15            16            11            10 
 13            22            11            7 
 12            15            9             10 
 12            15            7             11 
 18            11            13            20 
 14            14            27            8 
 13            16            9             11 
 10            13            12            9 
 16            10            10            16 
 19            15            14            11 
 7             7             11            11 
 13            16            12            11 
 7             11            19            10 
 10            15            14            12 
 13            11            12            8 
 12            10            5             10 
 9             11            10            10 
 11            11            10            8 
 13            10            7             10 
 12            11            11            10 
 5             8             10            9 
 9             11            9             8 
 14            14            14            8 
 9             13            14            10 
 8             16            10            13 
 4             14            7             17 
 11            10            15            9 
 12            7             8             5 
 8             10            9             7 
 9             14            13            15 
 9             6             11            8 
 9             10            7             5 
 5             10            7             9 
 9             7             10            9 
 12            7             17            7 
 8             10            3             8 
 10            2             5             3 
 8             9             9             6 
 3             6             6             12 
 7             8             5             11 
 6             11            4             11 
 11            5             12            5 
 8             5             5             5 
 6             8             3             9 
 7             8             8             2 
 7             6             3             8 
 11            7             10            10 
 3             8             10            9 
 9             8             9             8 
 6             5             10            8 
 8             7             4             7 
 3             7             4             5 
 7             7             11            7 
 3             2             3             7 
 5             9             1             8 
 9             8             8             6 
 7             5             8             3 
 10            5             11            8 
 3             7             8             7 
 6             9             1             0 
 2             4             3             3 
 3             7             4             2 
 7             1             3             2 
 6             4             2             1 
 7             5             6             5 
 4             2             4             5 
 2             4             6             3 
 3             3             5             4 
 1             4             1             2 
 5             2             3             3 
 5             5             4             5 
 5             4             2             5 
 0             4             1             3 
 5             2             1             4 
 2             2             4             0 
 2             5             1             3 
 3             5             6             4 
 2             0             1             3 
 4             2             1             0 
 2             3             1             1 
 1             2             2             4 
 4             2             2             1 
 6             3             6             1 
 1             1             3             4 
 1             2             4             5 
 2             3             2             5 
 1             1             1             4 
 0             2             1             6 
 1             1             1             1 
 2             2             1             1 
 0             5             2             3 
 5             2             4             5 
 2             3             2             3 
 1             2             2             3 
 3             6             3             3 
 5             2             4             1 
 2             2             1             0 
 2             4             3             4 
 3             3             1             3 
 2             1             4             0 
 3             2             1             3 
 3             1             1             3 
 3             6             6             5 
 3             2             3             5 
 2             1             1             2 
 2             2             3             1 
 1             2             2             0 
 3             3             0             1 
 5             1             1             4 
 3             1             0             2 
 0             1             2             2 
 0             2             3             2 
 5             1             1             2 
 2             3             3             1 
 0             3             1             1 
 0             1             3             0 
 3             0             3             1 
 2             0             2             3 
 1             5             2             0 
 0             1             4             0 
 1             1             4             0 
 0             1             2             2 
 1             5             2             2 
 5             1             5             0 
 3             5             5             0 
 2             2             2             1 
 2             5             3             3 
 7             6             4             3 
 3             3             2             2 
 2             1             2             0 
 3             4             4             6 
 4             4             2             1 
 3             1             0             0 


