Empty File 'c:\RBS\data\2026\07\VNM1313.RBS
Identifier 'VNM1313.RBS  170 Degree RBS LT =  1467.894 RT  1472.387 Gain  2
Date       '08:34:14  07-02-2026
Conversion  1.59             48 
MeV 1.902
Beam He+
Geometry General
Theta -09.0
Phi  11
Psi 20.0
Omega 2.7
Choff 0 FWHM 15
Current 007.36
Charge 10
Swallow
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 831           1187          1180          1103 
 1121          1046          1049          1045 
 1060          1065          1052          984 
 938           944           933           954 
 893           915           909           823 
 834           889           847           853 
 860           826           839           780 
 746           782           774           757 
 732           744           738           780 
 747           714           751           738 
 726           752           685           676 
 715           631           653           647 
 646           632           634           646 
 638           613           606           644 
 598           601           650           626 
 577           601           572           593 
 574           612           585           592 
 599           548           554           559 
 569           555           538           539 
 545           523           524           500 
 583           531           517           517 
 478           509           516           522 
 514           532           524           499 
 504           494           502           468 
 489           467           495           517 
 473           502           474           442 
 485           417           474           441 
 437           475           470           450 
 445           460           440           463 
 418           414           441           412 
 434           439           427           416 
 429           437           450           413 
 456           430           400           416 
 417           391           415           413 
 359           363           372           359 
 418           420           398           406 
 422           390           401           404 
 424           398           411           375 
 368           426           377           416 
 380           382           354           348 
 349           412           382           374 
 398           350           377           351 
 368           386           422           365 
 355           330           355           357 
 406           338           381           350 
 313           382           331           342 
 359           331           356           363 
 363           376           380           325 
 367           349           346           371 
 327           308           314           361 
 316           346           323           342 
 329           330           322           327 
 299           300           327           311 
 288           255           257           199 
 184           163           104           99 
 66            65            53            39 
 26            18            15            14 
 8             13            11            9 
 8             9             10            6 
 7             9             6             5 
 6             11            5             6 
 3             3             3             5 
 3             7             5             7 
 3             5             2             4 
 7             6             2             1 
 3             6             3             1 
 0             2             1             5 
 2             2             3             3 
 3             3             1             3 
 3             3             4             4 
 4             1             2             4 
 6             6             5             11 
 7             7             7             10 
 6             10            5             3 
 7             2             3             7 
 4             2             2             2 
 1             1             1             1 
 3             2             1             3 
 2             0             2             2 
 0             0             2             1 
 6             4             1             3 
 2             2             0             1 
 1             0             5             3 
 2             1             0             0 
 1             0             0             6 
 3             4             2             5 
 9             8             18            19 
 12            25            36            42 
 35            40            59            46 
 40            38            25            25 
 18            11            1             7 
 4             1             2             6 
 0             2             1             1 
 3             0             4             0 
 1             0             0             0 
 2             2             1             1 
 1             0             2             1 
 0             0             1             1 
 1             0             1             0 
 0             0             0             1 
 0             0             0             1 
 2             1             3             2 
 0             0             0             0 
 0             1             1             0 
 0             0             0             2 
 0             1             0             1 
 1             1             3             2 
 1             0             1             1 
 0             0             0             0 
 0             0             1             1 
 0             0             1             1 
 0             2             0             0 
 0             1             1             1 
 0             0             1             1 
 0             0             0             1 
 3             1             1             0 
 0             0             1             2 
 0             0             1             0 
 1             0             0             2 
 0             1             1             0 
 0             1             0             0 
 4             3             0             1 
 1             1             0             0 
 1             0             1             0 
 0             0             1             1 
 0             0             0             1 
 0             0             1             0 
 0             2             1             0 
 0             1             1             2 
 0             0             2             0 
 0             1             0             1 
 0             1             0             0 
 1             0             0             2 
 0             1             1             1 
 0             0             0             1 
 1             0             0             2 
 1             2             1             0 
 2             1             1             0 
 0             0             0             1 
 1             2             1             0 
 0             0             2             0 
 0             0             0             0 
 0             0             1             0 
 1             0             0             1 
 1             1             0             0 
 0             1             0             0 
 1             0             0             1 
 0             1             1             0 
 0             1             2             0 
 0             0             0             0 
 2             1             0             0 
 2             0             0             0 
 2             1             0             0 
 1             1             1             0 
 0             0             1             0 
 3             0             1             0 
 0             0             0             0 
 1             0             0             0 
 0             1             1             0 
 0             0             0             0 
 0             1             0             0 
 0             0             0             1 
 0             1             0             0 
 1             1             0             1 
 0             0             0             1 
 1             0             1             1 
 1             1             0             0 
 0             0             0             1 
 1             0             1             0 
 1             0             0             0 
 1             1             1             0 
 0             1             0             0 
 1             0             0             0 
 0             2             3             1 
 0             1             0             0 
 1             0             1             2 
 0             0             0             0 
 1             0             0             0 
 0             0             1             2 
 2             0             0             1 
 1             1             0             0 
 2             1             1             0 
 2             2             2             0 
 0             1             0             1 
 1             0             1             1 
 1             3             0             0 
 1             1             2             0 
 0             4             2             0 
 1             2             0             0 
 1             0             1             0 
 1             2             0             3 
 1             0             1             1 
 2             2             0             3 
 3             3             3             4 
 4             4             0             2 
 3             5             3             2 
 2             1             5             4 
 9             9             4             5 
 12            10            16            10 
 21            30            39            60 
 95            141           153           237 
 284           398           573           662 
 847           953           1043          1186 
 1222          1230          1318          1208 
 1098          976           823           655 
 508           431           294           200 
 127           92            42            27 
 28            11            5             8 
 6             3             1             2 
 1             2             2             2 
 1             4             6             4 
 5             3             7             5 
 5             10            10            11 
 22            16            31            36 
 67            70            99            145 
 181           192           284           324 
 376           437           486           545 
 589           521           538           553 
 510           455           415           347 
 300           265           199           183 
 133           106           59            54 
 27            18            10            6 
 4             2             0             1 
 1             0             2             0 
 0             1             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             1             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             1 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 1             1             0             0 
 2             0             1             1 
 1             3             1             2 
 0             1             1             1 
 1             1             0             3 
 0             2             0             0 
 0             1             0             1 
 0             0             0             0 
 0             1             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 
 0             0             0             0 


