"""Generate pyRUMP's PIXE atomic-data tables from xraylib.

pyRUMP ships these tables instead of depending on xraylib at run time, the
same way it ships ``atom4.dat``: installs stay light, and results only change
when the tables are deliberately regenerated (and git shows it). Only this
script needs xraylib::

    pip install xraylib
    python tools/pixe_atomic.py            # writes src/pyrump/data/pixe/

Tables written (all CSV, ``#`` lines are comments):

* ``xray_lines.csv`` -- every IUPAC line (``KL3``, ``L3M5``, ``M5N7`` ...) from
  the K, L1-L3 and M1-M5 subshells with a radiative rate and an energy of at
  least 50 eV (the attenuation grid's lower end):
  ``Z, symbol, line, shell, energy_keV, rate``. ``rate`` is xraylib's
  ``RadRate``: the line's share of the radiative decays of a vacancy in
  ``shell``.
* ``xray_shells.csv`` -- per subshell K-M5: ``Z, symbol, shell, edge_keV,
  fluor_yield, jump_factor``.
* ``coster_kronig.csv`` -- the *direct* Coster-Kronig probabilities ``f_ij``
  (``L12, L13, L23, M12 ... M45``). xraylib's ``FLP13`` (f'13 = f13 +
  f12 f23) is left out on purpose: the vacancy cascade adds the f12 f23 path
  itself, and using f'13 as well would count it twice.
* ``mass_attenuation.csv.gz`` -- total mass attenuation coefficient
  ``CS_Total`` (cm^2/g) from 0.1 keV (where xraylib's data begin) to 100 keV,
  sampled so that log-log interpolation between neighbouring points
  reproduces ``CS_Total`` to :data:`MU_TOLERANCE`. Starting from a log grid,
  every interval whose midpoint is off by more is bisected, again and
  again. That settles the absorption jumps by itself -- each ends up
  bracketed by two points 1e-9 apart -- without relying on ``EdgeEnergy``,
  whose values are not exactly where ``CS_Total`` jumps, and it also
  resolves the fine structure just above an edge.

The binding energies are the same xraylib edge energies the ECPSSR
ionisation tables were computed with, so the two stay consistent.
"""

from __future__ import annotations

import argparse
import csv
import gzip
import re
from datetime import date
from pathlib import Path

import numpy as np
import xraylib as xr

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = ROOT / "src" / "pyrump" / "data" / "pixe"

Z_RANGE = range(1, 93)
SHELLS = ["K", "L1", "L2", "L3", "M1", "M2", "M3", "M4", "M5"]
CK_TRANSITIONS = [
    "L12", "L13", "L23",
    "M12", "M13", "M14", "M15", "M23", "M24", "M25", "M34", "M35", "M45",
]
#: An IUPAC line from a subshell PIXE uses: initial subshell, final subshell.
IUPAC = re.compile(r"(K|L[1-3]|M[1-5])([K-Q][1-7])")

#: Attenuation grid: 0.1 keV to 100 keV, 60 points per decade.
E_MIN_KEV, E_MAX_KEV, PER_DECADE = 0.1, 100.0, 60
#: Relative accuracy of log-log interpolation in the attenuation table, and
#: the narrowest interval refinement goes down to (a jump's bracket).
MU_TOLERANCE, MIN_INTERVAL = 1e-3, 1e-9


def _header(what: str) -> list[str]:
    return [
        f"# {what}",
        f"# Generated by tools/pixe_atomic.py from xraylib {xr.__version__} on {date.today()}.",
        "# xraylib: T. Schoonjans et al., Spectrochim. Acta B 66 (2011) 776. BSD licence;",
        "# see src/pyrump/data/SOURCES.md for its copyright notice.",
    ]


def _call(function, *args) -> float | None:
    """An xraylib value, or None where it has no data."""
    try:
        value = function(*args)
    except ValueError:
        return None
    return value if value and value > 0 else None


def _lines() -> list[str]:
    names = sorted(
        (name[:-5] for name in dir(xr) if name.endswith("_LINE") and IUPAC.fullmatch(name[:-5])),
        key=lambda n: (SHELLS.index(IUPAC.fullmatch(n).group(1)), n),
    )
    rows = ["Z,symbol,line,shell,energy_keV,rate"]
    for z in Z_RANGE:
        symbol = xr.AtomicNumberToSymbol(z)
        for name in names:
            macro = getattr(xr, f"{name}_LINE")
            energy = _call(xr.LineEnergy, z, macro)
            rate = _call(xr.RadRate, z, macro)
            if energy and rate and energy >= E_MIN_KEV:
                shell = IUPAC.fullmatch(name).group(1)
                rows.append(f"{z},{symbol},{name},{shell},{energy:.6g},{rate:.6g}")
    return rows


def _shells() -> list[str]:
    rows = ["Z,symbol,shell,edge_keV,fluor_yield,jump_factor"]
    for z in Z_RANGE:
        symbol = xr.AtomicNumberToSymbol(z)
        for shell in SHELLS:
            macro = getattr(xr, f"{shell}_SHELL")
            edge = _call(xr.EdgeEnergy, z, macro)
            if edge is None:
                continue
            omega = _call(xr.FluorYield, z, macro) or 0.0
            jump = _call(xr.JumpFactor, z, macro) or 0.0
            rows.append(f"{z},{symbol},{shell},{edge:.6g},{omega:.6g},{jump:.6g}")
    return rows


def _coster_kronig() -> list[str]:
    rows = ["Z,symbol,transition,probability"]
    for z in Z_RANGE:
        symbol = xr.AtomicNumberToSymbol(z)
        for transition in CK_TRANSITIONS:
            value = _call(xr.CosKronTransProb, z, getattr(xr, f"F{transition}_TRANS"))
            if value is not None:
                rows.append(f"{z},{symbol},{transition},{value:.6g}")
    return rows


def _mu(z: int, energy: float) -> float | None:
    return _call(xr.CS_Total, z, float(energy))


def _refined(z: int, grid: np.ndarray) -> list[tuple[float, float]]:
    """``(energy, mu)`` points on which log-log interpolation reproduces
    ``CS_Total`` to :data:`MU_TOLERANCE`."""
    points = {e: mu for e in grid if (mu := _mu(z, e)) is not None}
    while True:
        energies = sorted(points)
        added = False
        for low, high in zip(energies, energies[1:]):
            if high / low - 1 < MIN_INTERVAL:
                continue
            # Three probes, not just the midpoint: a step inside the interval
            # can make the midpoint agree with the interpolation by chance.
            if any(_misfit(z, low, high, points, f) for f in (0.25, 0.5, 0.75)):
                middle = float(np.sqrt(low * high))
                points[middle] = _mu(z, middle)
                added = True
        if not added:
            return sorted(points.items())


def _misfit(z: int, low: float, high: float, points: dict, fraction: float) -> bool:
    """Whether log-log interpolation between ``low`` and ``high`` misses
    ``CS_Total`` by more than :data:`MU_TOLERANCE` at ``fraction`` of the
    way across (in log energy)."""
    energy = float(low * (high / low) ** fraction)
    mu = _mu(z, energy)
    if mu is None:
        return False
    guess = points[low] ** (1 - fraction) * points[high] ** fraction
    return abs(guess / mu - 1) > MU_TOLERANCE


def _attenuation() -> list[str]:
    decades = np.log10(E_MAX_KEV / E_MIN_KEV)
    grid = np.geomspace(E_MIN_KEV, E_MAX_KEV, int(round(decades * PER_DECADE)) + 1)
    rows = ["Z,symbol,energy_keV,mu_cm2_g"]
    for z in Z_RANGE:
        symbol = xr.AtomicNumberToSymbol(z)
        for energy, mu in _refined(z, grid):
            rows.append(f"{z},{symbol},{energy:.12g},{mu:.7g}")
    return rows


def write(out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    tables = {
        "xray_lines.csv": ("X-ray lines: energy and radiative rate", _lines),
        "xray_shells.csv": ("Subshells: edge, fluorescence yield, jump factor", _shells),
        "coster_kronig.csv": ("Direct Coster-Kronig probabilities f_ij", _coster_kronig),
    }
    for name, (what, build) in tables.items():
        rows = build()
        (out / name).write_text("\n".join(_header(what) + rows) + "\n", encoding="utf-8")
        print(f"{name}: {len(rows) - 1} rows")
    rows = _attenuation()
    text = "\n".join(_header("Total mass attenuation coefficient (CS_Total)") + rows) + "\n"
    with gzip.open(out / "mass_attenuation.csv.gz", "wt", encoding="utf-8") as handle:
        handle.write(text)
    print(f"mass_attenuation.csv.gz: {len(rows) - 1} rows")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("out", nargs="?", type=Path, default=DEFAULT_OUT)
    write(parser.parse_args().out)


if __name__ == "__main__":
    main()
